fix: Use the new Codecov uploader
codefresh-io/steps pull request #374
Opened 2021-08-05 16:53 UTC by thomasrockhu-codecov

Uses the new Codecov uploader as documented [here](https://docs.codecov.com/docs/codecov-uploader)

2021-08-05 18:09 UTC, hseligson1 approved these changes

2021-08-05 18:20 UTC, hseligson1 approved these changes
Updating step for Codecov changes.

2021-10-02 17:18 UTC, pasha-codefresh requested changes

2021-10-02 17:18 UTC, pasha-codefresh commented on incubating/codecov-reporter/step.yaml
> +            "os"
It is breaking change, will cause problem with existing customers, I think we should add at least some default value

2021-10-02 17:18 UTC, pasha-codefresh commented on incubating/codecov-reporter/step.yaml
> +                "description": "OS being used ( alpline | linux | macos | windows )"
here is typo
alpline

2021-10-04 08:57 UTC, pasha-codefresh requested changes

2021-10-04 08:57 UTC, pasha-codefresh commented on incubating/codecov-reporter/step.yaml
> +        - ./codecov -t ${{CODECOV_API_KEY}} -Q codefresh-2.0.0 | tee codecov.log
when i execute it , ./codecov can`t be found

2021-10-04 13:37 UTC, pasha-codefresh commented
@thomasrockhu-codecov Thank you for your contribution, it is merged 
https://github.com/codefresh-io/steps/pull/399 
I created another Pr because I did changes

2021-10-04 13:37 UTC, closed without merging